// Read this file first when changing release/version metadata.
// Purpose: central GUI release metadata and about-dialog text.
// Scope: build-time values are generated by build-gui.ps1 into EmbeddedScripts.cs.

static class AppInfo
{
    public const string ProductName = "AI Agent Secure";
    public const string CoreName = "Shell-Secure";
    public const string Version = "1.0.2";
    public const string Author = "Joel Aniol";
    public const string ProjectUrl = "https://github.com/joelaniol/ai-agent-secure";

    public static string BuildId
    {
        get { return string.IsNullOrWhiteSpace(EmbeddedScripts.BuildId) ? "unknown" : EmbeddedScripts.BuildId; }
    }

    public static string BuildCommit
    {
        get { return string.IsNullOrWhiteSpace(EmbeddedScripts.BuildCommit) ? "unknown" : EmbeddedScripts.BuildCommit; }
    }

    public static string BuildTimeUtc
    {
        get { return string.IsNullOrWhiteSpace(EmbeddedScripts.BuildTimeUtc) ? "unknown" : EmbeddedScripts.BuildTimeUtc; }
    }
}
