// Read this file first when adding/changing localizable GUI strings.
// Purpose: key-based localization for the GUI surface. Mirrors the
//          Bash _ss_t() helper architecture so EN/DE switching stays
//          consistent across protection layer, TUI, CLI, and GUI.
// Scope: covers GUI text only. Block-message bodies for the bash
//        runtime live in lib/protection-i18n.sh and the per-renderer
//        EN/DE pairs inside protection-{delete,ps,git}.sh.

using System;
using System.Collections.Generic;

static class Loc
{
    // Active language code. Defaults to "en"; flipped to "de" by Init()
    // when the parsed config explicitly requests German. Anything else
    // resolves to English so future locales fail safely instead of
    // silently dropping back to half-localised state.
    public static string Lang = "en";

    public static void Init(string raw)
    {
        Lang = string.Equals(raw, "de", StringComparison.OrdinalIgnoreCase) ? "de" : "en";
    }

    static readonly Dictionary<string, string> En = new Dictionary<string, string>
    {
        { "smoke.ready", "Ready" },
        { "common.install", "Install" },
        { "common.update", "Update" },
        { "common.uninstall", "Uninstall" },
        { "common.refresh", "Refresh" },
        { "common.clear", "Clear" },
        { "common.remove", "Remove" },
        { "common.add", "Add" },
        { "common.cancel", "Cancel" },
        { "common.ok", "Got it" },

        { "fatal.message", "AI Agent Secure exited because of an unhandled error.\n\n{0}" },
        { "fatal.title", "AI Agent Secure Error" },
        { "tray.show", "Show" },
        { "tray.about", "About" },
        { "tray.exit", "Exit" },

        { "nav.dashboard", "Dashboard" },
        { "nav.folders", "Protected Areas" },
        { "nav.settings", "Settings" },
        { "nav.log", "Log" },
        { "nav.about", "About" },
        { "sidebar.install", "\u2B07 Install" },
        { "sidebar.installed", "\u2714 Installed" },
        { "sidebar.update", "\u21BB Update" },
        { "sidebar.uninstall", "\u2716 Uninstall" },

        { "dashboard.title", "Dashboard" },
        { "dashboard.subtitle", "Protection overview" },
        { "dashboard.update.title", "Update available" },
        { "dashboard.update.hint", "This GUI contains newer protection layers than your installation. Click \"Update now\" to activate them. Your configuration and whitelist stay intact." },
        { "dashboard.update.button", "Update now" },
        { "dashboard.stat.dirs", "Protected areas" },
        { "dashboard.stat.whitelist", "Exceptions" },
        { "dashboard.stat.blocked", "Blocked" },
        { "dashboard.banner.not_installed", "Protection is not installed" },
        { "dashboard.banner.full", "Full protection is active" },
        { "dashboard.banner.partial", "Protection is partially active" },
        { "dashboard.banner.repair", "Protection needs repair" },
        { "dashboard.banner.disabled", "Protection is off!" },
        { "dashboard.status.not_installed", "Not installed" },
        { "dashboard.status.not_installed_hint", "Click \"Install\" on the left to set up protection" },
        { "dashboard.status.on", "Protection is ON" },
        { "dashboard.status.full_hint", "Interactive and non-interactive Bash sessions are protected against dangerous delete commands" },
        { "dashboard.status.partial_hint", "Interactive shells are prepared. For full protection, set BASH_ENV or reload your shells." },
        { "dashboard.status.repair_title", "Protection incomplete" },
        { "dashboard.status.repair_hint", "The configuration is active, but neither .bashrc nor BASH_ENV is set correctly." },
        { "dashboard.status.off", "Protection is OFF" },
        { "dashboard.status.off_hint", "Your areas are not protected!" },

        { "folders.title", "Protected Areas" },
        { "folders.subtitle", "These areas can be folders, projects, or entire drives" },
        { "folders.add", "\U0001F4C1  Add area" },
        { "folders.empty.title", "No areas protected yet" },
        { "folders.empty.hint", "Click \"Add area\" in the top right to get started" },

        { "settings.title", "Settings" },
        { "settings.subtitle", "Adjust protection and system options" },
        { "settings.language.title", "Language" },
        { "settings.language.hint", "Switches block messages, GUI, and notifications between English and German." },
        { "settings.language.en", "English" },
        { "settings.language.de", "Deutsch" },
        { "action.change_language", "change language" },
        { "settings.categories.title", "Protection Categories" },
        { "settings.categories.hint", "Control individual protection types independently. The master switch on the dashboard always disables everything at once." },
        { "settings.delete.title", "Delete Protection" },
        { "settings.delete.hint", "Blocks 'rm -rf', 'cmd rmdir /s', and PowerShell 'Remove-Item -Recurse' inside protected areas." },
        { "settings.git.title", "Git Protection" },
        { "settings.git.hint", "Blocks 'git stash' on a dirty worktree, preventing lost work from agents that stash and never pop." },
        { "settings.git_flood.title", "Git Flood Protection" },
        { "settings.git_flood.hint", "Slows runaway agents by blocking after too many network git calls (push/pull/fetch) in the time window." },
        { "settings.flood_threshold.title", "Flood threshold" },
        { "settings.flood_threshold.hint", "Maximum number of network git calls per time window before blocking." },
        { "settings.flood_window.title", "Flood time window (seconds)" },
        { "settings.flood_window.hint", "Time span in which calls are counted. Default: 60 seconds." },
        { "settings.http_api.title", "HTTP/API Protection" },
        { "settings.http_api.hint", "Blocks authenticated curl calls that look like destructive API deletes, such as DELETE or delete mutations." },
        { "settings.ps_utf8.title", "Require PowerShell UTF-8" },
        { "settings.ps_utf8.hint", "Blocks PowerShell writes without -Encoding utf8, preventing UTF-16 BOM corruption in source files." },
        { "settings.details.toggle", "Show protection details" },
        { "settings.details.blocked", "Blocked" },
        { "settings.details.allowed", "Allowed" },
        { "settings.details.delete.blocked.rm", "rm -rf inside protected areas" },
        { "settings.details.delete.blocked.cmd", "cmd /c rmdir /s /q inside protected areas" },
        { "settings.details.delete.blocked.ps", "PowerShell Remove-Item -Recurse inside protected areas" },
        { "settings.details.delete.blocked.cwd", "rmdir /s with an unclear target while the current directory is protected" },
        { "settings.details.delete.allowed.files", "Single-file deletes and non-recursive deletes" },
        { "settings.details.delete.allowed.safe", "Allowed exception names such as node_modules, dist, build, or .cache" },
        { "settings.details.delete.allowed.outside", "Deletes outside protected areas" },
        { "settings.details.git.blocked.stash_dirty", "git stash / push / save when the worktree contains changes" },
        { "settings.details.git.blocked.stash_mutation", "git stash pop, apply, drop, clear, store, and other stash mutations" },
        { "settings.details.git.blocked.reset", "git reset --hard when tracked changes would be lost" },
        { "settings.details.git.blocked.clean", "git clean -f when files would actually be removed" },
        { "settings.details.git.blocked.overwrite", "checkout, switch, or restore forms that would overwrite local changes" },
        { "settings.details.git.blocked.branch", "git branch -D when the branch still has unmerged commits" },
        { "settings.details.git.allowed.stash_read", "git stash list, show, create, and help" },
        { "settings.details.git.allowed.clean_dry", "git clean dry-runs and interactive clean" },
        { "settings.details.git.allowed.clean_tree", "Clean worktrees and no-op commands" },
        { "settings.details.git.allowed.reset_soft", "git reset --soft, --mixed, and path-limited reset forms" },
        { "settings.details.flood.blocked.network", "Repeated push, pull, fetch, clone, or ls-remote calls" },
        { "settings.details.flood.blocked.threshold", "More calls than the configured threshold within the time window" },
        { "settings.details.flood.blocked.agent_loop", "Runaway loops that keep hitting remote git operations" },
        { "settings.details.flood.allowed.local", "Local git commands such as status, log, diff, branch, or commit" },
        { "settings.details.flood.allowed.under_limit", "Network calls while they stay under the threshold" },
        { "settings.details.flood.allowed.window_reset", "New calls after the configured time window has passed" },
        { "settings.details.http.blocked.delete", "Authenticated curl -X DELETE requests" },
        { "settings.details.http.blocked.destructive_payload", "Authenticated POST, PUT, or PATCH requests with action/operation fields, GraphQL mutations, or destructive API paths" },
        { "settings.details.http.blocked.authenticated", "Provider API calls carrying bearer tokens, API keys, cookies, netrc auth, or basic auth" },
        { "settings.details.http.allowed.readonly", "Read-only curl requests, search/query payloads, preview endpoints, and unauthenticated API calls" },
        { "settings.details.http.allowed.unauthenticated", "Destructive-looking examples without credentials, useful for docs or tests" },
        { "settings.details.http.allowed.permission", "Re-running after explicit user permission and resource verification" },
        { "settings.details.ps.blocked.cmdlets", "Set-Content, Add-Content, and Out-File writes without -Encoding utf8" },
        { "settings.details.ps.blocked.redirect", "PowerShell redirection writes such as > and >>" },
        { "settings.details.ps.blocked.dotnet", ".NET file writes with unsafe encodings such as Unicode, ASCII, or UTF7" },
        { "settings.details.ps.allowed.encoding", "Writes with explicit UTF-8 encoding" },
        { "settings.details.ps.allowed.gitbash", "Writes performed directly from Git Bash" },
        { "settings.details.ps.allowed.readonly", "Read-only PowerShell commands" },
        { "settings.autostart.title", "Start with Windows" },
        { "settings.autostart.hint", "AI Agent Secure starts automatically with Windows" },
        { "settings.system.title", "System status" },
        { "settings.git_bash.found", "\u2714  Git Bash: {0}" },
        { "settings.git_bash.missing", "\u2716  Git Bash not found!" },
        { "settings.bash_env.full", "\u2714  BASH_ENV set - Bash sessions protected" },
        { "settings.bash_env.chained", "\u2714  BASH_ENV chained - AI Agent Secure and the existing loader are active" },
        { "settings.bash_env.foreign", "\u2716  BASH_ENV points somewhere else - AI Agent Secure is not active everywhere" },
        { "settings.bash_env.missing", "\u26A0  BASH_ENV not set - only interactive shells are protected" },
        { "settings.whitelist.title", "Allowed Exceptions" },
        { "settings.whitelist.hint", "Folders with these names may still be deleted, for example build artifacts" },
        { "settings.whitelist.add", "+ Add" },

        { "log.title", "Log" },
        { "log.subtitle", "All blocked delete attempts" },
        { "log.empty.title", "No threats blocked" },
        { "log.empty.hint", "Everything looks good!" },

        { "about.title", "About AI Agent Secure" },
        { "about.subtitle", "Release and project information" },
        { "about.core", "Protection core: {0}" },
        { "about.version", "Version: {0}" },
        { "about.build", "Build: {0}" },
        { "about.commit", "Commit: {0}" },
        { "about.built", "Built: {0} UTC" },
        { "about.author", "Author: {0}" },
        { "about.project", "Project: {0}" },

        { "action.toggle_delete", "toggle Delete Protection" },
        { "action.toggle_git", "toggle Git Protection" },
        { "action.toggle_git_flood", "toggle Git Flood Protection" },
        { "action.change_flood_threshold", "change flood threshold" },
        { "action.change_flood_window", "change flood time window" },
        { "action.toggle_http_api", "toggle HTTP/API Protection" },
        { "action.toggle_ps_utf8", "toggle PowerShell UTF-8 requirement" },
        { "action.add_folder", "add area" },
        { "action.remove_exception", "remove exception" },
        { "action.clear_log", "clear log" },
        { "dialog.folder_picker", "Select the folder or drive to protect:" },
        { "dialog.remove_dir.message", "Remove protection for this area?\n\n{0}\n\nThe path itself will NOT be deleted." },
        { "dialog.remove_dir.title", "Remove protection" },
        { "dialog.add_exception.title", "Add exception" },
        { "dialog.add_exception.prompt", "Which folder name may still be deleted?\n\nExamples: .mypy_cache, .sass-cache, obj" },
        { "dialog.clear_log.message", "Really clear the log?" },
        { "dialog.clear_log.title", "Clear log" },
        { "dialog.git_bash_missing.message", "Git Bash was not found.\n\nAI Agent Secure needs Git Bash, so installation is cancelled." },
        { "dialog.git_bash_missing.title", "Git Bash missing" },
        { "dialog.uninstall.message", "Really remove AI Agent Secure completely?" },
        { "dialog.uninstall.title", "Uninstall" },
        { "dialog.save_failed", "Configuration could not be saved." },
        { "config.load_failed", "Configuration could not be loaded: {0}" },
        { "config.not_installed", "AI Agent Secure is not installed yet." },
        { "config.save_failed", "Configuration could not be saved: {0}" },
        { "dialog.install_required.title", "Installation required" },
        { "dialog.install_required.message", "AI Agent Secure is not installed yet.\n\nPlease install first before you use \"{0}\"." },

        { "toast.multi", "Multiple actions blocked" },
        { "toast.git_flood", "Git flood blocked" },
        { "toast.http_api", "HTTP API call blocked" },
        { "toast.ps_utf8", "PowerShell write blocked" },
        { "toast.git", "Git action blocked" },
        { "toast.delete", "Delete attempt blocked" },
        { "toast.details", "Click for details in the log." },
        { "toast.one_prevented", "One attempt was prevented." },
        { "toast.many_prevented", "{0} attempts were prevented." },

        { "installer.error_prefix", "Error: {0}" },
        { "installer.git_bash_missing", "Error: Git Bash was not found. Installation cancelled." },
        { "installer.protection_installed", "Protection module installed" },
        { "installer.default_config_created", "Default settings created" },
        { "installer.existing_config_kept", "Existing settings kept" },
        { "installer.shell_config_updated", "Shell configuration updated" },
        { "installer.bash_env_correct", "BASH_ENV is already set correctly" },
        { "installer.bash_env_enabled", "BASH_ENV enabled for non-interactive Bash shells" },
        { "installer.bash_env_chained", "BASH_ENV was chained with the existing loader" },
        { "installer.shortcut_created", "Start Menu shortcut created (for Windows notifications)" },
        { "installer.shortcut_warning", "Warning: Start Menu shortcut could not be created ({0})" },
        { "installer.install_done", "\nDone! Protection is now active." },
        { "installer.log_backup", "Log saved: {0}" },
        { "installer.removed", "Protection was completely removed." },
        { "installer.install_first", "Please install first." },
        { "installer.updated", "Protection module was updated." }
    };

    static readonly Dictionary<string, string> De = new Dictionary<string, string>
    {
        { "smoke.ready", "Bereit" },
        { "common.install", "Installieren" },
        { "common.update", "Aktualisieren" },
        { "common.uninstall", "Deinstallieren" },
        { "common.refresh", "Aktualisieren" },
        { "common.clear", "Leeren" },
        { "common.remove", "Entfernen" },
        { "common.add", "Hinzufügen" },
        { "common.cancel", "Abbrechen" },
        { "common.ok", "Verstanden" },

        { "fatal.message", "AI Agent Secure ist mit einem unbehandelten Fehler beendet worden.\n\n{0}" },
        { "fatal.title", "AI Agent Secure Fehler" },
        { "tray.show", "Anzeigen" },
        { "tray.about", "\u00DCber" },
        { "tray.exit", "Beenden" },

        { "nav.dashboard", "Dashboard" },
        { "nav.folders", "Geschützte Bereiche" },
        { "nav.settings", "Einstellungen" },
        { "nav.log", "Protokoll" },
        { "nav.about", "\u00DCber" },
        { "sidebar.install", "\u2B07 Installieren" },
        { "sidebar.installed", "\u2714 Installiert" },
        { "sidebar.update", "\u21BB Aktualisieren" },
        { "sidebar.uninstall", "\u2716 Deinstallieren" },

        { "dashboard.title", "Dashboard" },
        { "dashboard.subtitle", "Übersicht deines Schutzes" },
        { "dashboard.update.title", "Aktualisierung verfügbar" },
        { "dashboard.update.hint", "Diese GUI bringt neuere Schutz-Layer mit als deine Installation. Klicke \"Jetzt aktualisieren\", um sie aktiv zu ziehen — deine Konfiguration und Whitelist bleiben erhalten." },
        { "dashboard.update.button", "Jetzt aktualisieren" },
        { "dashboard.stat.dirs", "Geschützte Bereiche" },
        { "dashboard.stat.whitelist", "Ausnahmen" },
        { "dashboard.stat.blocked", "Blockiert" },
        { "dashboard.banner.not_installed", "Schutz ist nicht installiert" },
        { "dashboard.banner.full", "Vollschutz ist aktiv" },
        { "dashboard.banner.partial", "Schutz ist teilweise aktiv" },
        { "dashboard.banner.repair", "Schutz braucht Reparatur" },
        { "dashboard.banner.disabled", "Schutz ist ausgeschaltet!" },
        { "dashboard.status.not_installed", "Nicht installiert" },
        { "dashboard.status.not_installed_hint", "Klicke links auf \"Installieren\" um den Schutz einzurichten" },
        { "dashboard.status.on", "Schutz ist AN" },
        { "dashboard.status.full_hint", "Interaktive und nicht-interaktive Bash-Sessions sind gegen gefährliche Löschbefehle geschützt" },
        { "dashboard.status.partial_hint", "Interaktive Shells sind vorbereitet. Für Vollschutz bitte BASH_ENV setzen oder Shells neu laden." },
        { "dashboard.status.repair_title", "Schutz unvollständig" },
        { "dashboard.status.repair_hint", "Die Konfiguration ist aktiv, aber weder .bashrc noch BASH_ENV sind korrekt gesetzt." },
        { "dashboard.status.off", "Schutz ist AUS" },
        { "dashboard.status.off_hint", "Deine Bereiche sind nicht geschützt!" },

        { "folders.title", "Geschützte Bereiche" },
        { "folders.subtitle", "Diese Bereiche können Ordner, Projekte oder ganze Laufwerke sein" },
        { "folders.add", "\U0001F4C1  Bereich hinzufügen" },
        { "folders.empty.title", "Noch keine Bereiche geschützt" },
        { "folders.empty.hint", "Klicke oben rechts auf \"Bereich hinzufügen\" um loszulegen" },

        { "settings.title", "Einstellungen" },
        { "settings.subtitle", "Schutz und Systemoptionen anpassen" },
        { "settings.language.title", "Sprache" },
        { "settings.language.hint", "Wechselt Block-Meldungen, GUI und Benachrichtigungen zwischen Englisch und Deutsch." },
        { "settings.language.en", "English" },
        { "settings.language.de", "Deutsch" },
        { "action.change_language", "Sprache umschalten" },
        { "settings.categories.title", "Schutz-Kategorien" },
        { "settings.categories.hint", "Einzelne Schutzarten unabhaengig steuern. Der Master-Schalter auf dem Dashboard deaktiviert immer alles auf einmal." },
        { "settings.delete.title", "Lösch-Schutz" },
        { "settings.delete.hint", "Blockiert 'rm -rf', 'cmd rmdir /s' und PowerShell 'Remove-Item -Recurse' in geschützten Bereichen." },
        { "settings.git.title", "Git-Schutz" },
        { "settings.git.hint", "Blockiert 'git stash' auf einem dirty Worktree (verhindert verlorene Arbeit durch Agents, die stashen und nie poppen)." },
        { "settings.git_flood.title", "Git Flood-Schutz" },
        { "settings.git_flood.hint", "Bremst durchdrehende Agents: blockiert nach zu vielen Netzwerk-git-Aufrufen (push/pull/fetch) im Zeitfenster." },
        { "settings.flood_threshold.title", "Flood-Schwellwert" },
        { "settings.flood_threshold.hint", "Maximale Anzahl Netzwerk-git-Aufrufe pro Zeitfenster, bevor blockiert wird." },
        { "settings.flood_window.title", "Flood-Zeitfenster (Sekunden)" },
        { "settings.flood_window.hint", "Zeitraum, in dem die Aufrufe gezaehlt werden. Default: 60 Sekunden." },
        { "settings.http_api.title", "HTTP/API-Schutz" },
        { "settings.http_api.hint", "Blockiert authentifizierte curl-Aufrufe, die wie destruktive API-Loeschungen aussehen, z.B. DELETE oder delete-Mutationen." },
        { "settings.ps_utf8.title", "PowerShell UTF-8 Pflicht" },
        { "settings.ps_utf8.hint", "Blockiert PowerShell-Writes ohne -Encoding utf8 (verhindert UTF-16-BOM-Korruption von Quellcode-Dateien)." },
        { "settings.details.toggle", "Schutzdetails anzeigen" },
        { "settings.details.blocked", "Blockiert" },
        { "settings.details.allowed", "Erlaubt" },
        { "settings.details.delete.blocked.rm", "rm -rf in geschützten Bereichen" },
        { "settings.details.delete.blocked.cmd", "cmd /c rmdir /s /q in geschützten Bereichen" },
        { "settings.details.delete.blocked.ps", "PowerShell Remove-Item -Recurse in geschützten Bereichen" },
        { "settings.details.delete.blocked.cwd", "rmdir /s mit unklarem Ziel, wenn das aktuelle Verzeichnis geschützt ist" },
        { "settings.details.delete.allowed.files", "Einzelne Dateien und nicht-rekursive Löschbefehle" },
        { "settings.details.delete.allowed.safe", "Erlaubte Ausnahmen wie node_modules, dist, build oder .cache" },
        { "settings.details.delete.allowed.outside", "Löschen außerhalb geschützter Bereiche" },
        { "settings.details.git.blocked.stash_dirty", "git stash / push / save, wenn der Worktree Änderungen enthält" },
        { "settings.details.git.blocked.stash_mutation", "git stash pop, apply, drop, clear, store und andere Stash-Mutationen" },
        { "settings.details.git.blocked.reset", "git reset --hard, wenn tracked Änderungen verloren gingen" },
        { "settings.details.git.blocked.clean", "git clean -f, wenn wirklich Dateien entfernt würden" },
        { "settings.details.git.blocked.overwrite", "checkout, switch oder restore Formen, die lokale Änderungen überschreiben würden" },
        { "settings.details.git.blocked.branch", "git branch -D, wenn der Branch noch ungemergte Commits enthält" },
        { "settings.details.git.allowed.stash_read", "git stash list, show, create und help" },
        { "settings.details.git.allowed.clean_dry", "git clean Dry-Runs und interaktives clean" },
        { "settings.details.git.allowed.clean_tree", "Saubere Worktrees und No-op-Kommandos" },
        { "settings.details.git.allowed.reset_soft", "git reset --soft, --mixed und pfadbezogene reset Formen" },
        { "settings.details.flood.blocked.network", "Wiederholte push, pull, fetch, clone oder ls-remote Aufrufe" },
        { "settings.details.flood.blocked.threshold", "Mehr Aufrufe als der konfigurierte Schwellwert im Zeitfenster" },
        { "settings.details.flood.blocked.agent_loop", "Durchlaufende Schleifen, die Remote-git dauerhaft anstoßen" },
        { "settings.details.flood.allowed.local", "Lokale git-Kommandos wie status, log, diff, branch oder commit" },
        { "settings.details.flood.allowed.under_limit", "Netzwerkaufrufe, solange sie unter dem Schwellwert bleiben" },
        { "settings.details.flood.allowed.window_reset", "Neue Aufrufe nachdem das konfigurierte Zeitfenster verstrichen ist" },
        { "settings.details.http.blocked.delete", "Authentifizierte curl -X DELETE Aufrufe" },
        { "settings.details.http.blocked.destructive_payload", "Authentifizierte POST-, PUT- oder PATCH-Aufrufe mit action/operation-Feldern, GraphQL-Mutationen oder destruktiven API-Pfaden" },
        { "settings.details.http.blocked.authenticated", "Provider-API-Aufrufe mit Bearer Token, API-Key, Cookies, netrc oder Basic Auth" },
        { "settings.details.http.allowed.readonly", "Read-only curl-Aufrufe, Search-/Query-Payloads, Preview-Endpunkte und nicht authentifizierte API-Aufrufe" },
        { "settings.details.http.allowed.unauthenticated", "Destruktiv aussehende Beispiele ohne Zugangsdaten, z.B. fuer Doku oder Tests" },
        { "settings.details.http.allowed.permission", "Erneutes Ausfuehren nach expliziter Nutzerfreigabe und Ressourcenpruefung" },
        { "settings.details.ps.blocked.cmdlets", "Set-Content, Add-Content und Out-File Writes ohne -Encoding utf8" },
        { "settings.details.ps.blocked.redirect", "PowerShell Redirect-Writes wie > und >>" },
        { "settings.details.ps.blocked.dotnet", ".NET File-Writes mit unsicheren Encodings wie Unicode, ASCII oder UTF7" },
        { "settings.details.ps.allowed.encoding", "Writes mit explizitem UTF-8-Encoding" },
        { "settings.details.ps.allowed.gitbash", "Writes direkt aus Git Bash" },
        { "settings.details.ps.allowed.readonly", "Read-only PowerShell-Kommandos" },
        { "settings.autostart.title", "Beim Hochfahren starten" },
        { "settings.autostart.hint", "AI Agent Secure startet automatisch mit Windows" },
        { "settings.system.title", "Systemstatus" },
        { "settings.git_bash.found", "\u2714  Git Bash: {0}" },
        { "settings.git_bash.missing", "\u2716  Git Bash nicht gefunden!" },
        { "settings.bash_env.full", "\u2714  BASH_ENV gesetzt \u2014 Bash-Sessions geschützt" },
        { "settings.bash_env.chained", "\u2714  BASH_ENV verkettet \u2014 AI Agent Secure und bestehender Loader sind aktiv" },
        { "settings.bash_env.foreign", "\u2716  BASH_ENV zeigt auf etwas anderes \u2014 AI Agent Secure greift nicht überall" },
        { "settings.bash_env.missing", "\u26A0  BASH_ENV nicht gesetzt \u2014 nur interaktive Shells geschützt" },
        { "settings.whitelist.title", "Erlaubte Ausnahmen" },
        { "settings.whitelist.hint", "Ordner mit diesen Namen dürfen trotzdem gelöscht werden (z.B. Build-Dateien)" },
        { "settings.whitelist.add", "+ Hinzufügen" },

        { "log.title", "Protokoll" },
        { "log.subtitle", "Alle blockierten Löschversuche" },
        { "log.empty.title", "Keine Bedrohungen blockiert" },
        { "log.empty.hint", "Alles in Ordnung!" },

        { "about.title", "\u00DCber AI Agent Secure" },
        { "about.subtitle", "Release- und Projektinformationen" },
        { "about.core", "Schutz-Core: {0}" },
        { "about.version", "Version: {0}" },
        { "about.build", "Build: {0}" },
        { "about.commit", "Commit: {0}" },
        { "about.built", "Gebaut: {0} UTC" },
        { "about.author", "Autor: {0}" },
        { "about.project", "Projekt: {0}" },

        { "action.toggle_delete", "Lösch-Schutz umschalten" },
        { "action.toggle_git", "Git-Schutz umschalten" },
        { "action.toggle_git_flood", "Git Flood-Schutz umschalten" },
        { "action.change_flood_threshold", "Flood-Schwellwert aendern" },
        { "action.change_flood_window", "Flood-Zeitfenster aendern" },
        { "action.toggle_http_api", "HTTP/API-Schutz umschalten" },
        { "action.toggle_ps_utf8", "PowerShell UTF-8 Pflicht umschalten" },
        { "action.add_folder", "Bereich hinzufügen" },
        { "action.remove_exception", "Ausnahme entfernen" },
        { "action.clear_log", "Protokoll leeren" },
        { "dialog.folder_picker", "Ordner oder Laufwerk auswählen, das geschützt werden soll:" },
        { "dialog.remove_dir.message", "Schutz für diesen Bereich entfernen?\n\n{0}\n\nDer Pfad selbst wird NICHT gelöscht." },
        { "dialog.remove_dir.title", "Schutz entfernen" },
        { "dialog.add_exception.title", "Ausnahme hinzufügen" },
        { "dialog.add_exception.prompt", "Welcher Ordnername soll trotzdem gelöscht werden dürfen?\n\nBeispiele: .mypy_cache, .sass-cache, obj" },
        { "dialog.clear_log.message", "Protokoll wirklich leeren?" },
        { "dialog.clear_log.title", "Protokoll leeren" },
        { "dialog.git_bash_missing.message", "Git Bash wurde nicht gefunden.\n\nAI Agent Secure braucht Git Bash und bricht die Installation deshalb ab." },
        { "dialog.git_bash_missing.title", "Git Bash fehlt" },
        { "dialog.uninstall.message", "AI Agent Secure wirklich komplett entfernen?" },
        { "dialog.uninstall.title", "Deinstallieren" },
        { "dialog.save_failed", "Konfiguration konnte nicht gespeichert werden." },
        { "config.load_failed", "Konfiguration konnte nicht geladen werden: {0}" },
        { "config.not_installed", "AI Agent Secure ist noch nicht installiert." },
        { "config.save_failed", "Konfiguration konnte nicht gespeichert werden: {0}" },
        { "dialog.install_required.title", "Installation erforderlich" },
        { "dialog.install_required.message", "AI Agent Secure ist noch nicht installiert.\n\nBitte zuerst installieren, bevor du \"{0}\" verwendest." },

        { "toast.multi", "Mehrere Aktionen blockiert" },
        { "toast.git_flood", "Git-Flood blockiert" },
        { "toast.http_api", "HTTP-API-Aufruf blockiert" },
        { "toast.ps_utf8", "PowerShell-Schreibvorgang blockiert" },
        { "toast.git", "Git-Aktion blockiert" },
        { "toast.delete", "Löschversuch blockiert" },
        { "toast.details", "Klicken für Details im Protokoll." },
        { "toast.one_prevented", "Ein Versuch wurde verhindert." },
        { "toast.many_prevented", "{0} Versuche wurden verhindert." },

        { "installer.error_prefix", "Fehler: {0}" },
        { "installer.git_bash_missing", "Fehler: Git Bash wurde nicht gefunden. Installation abgebrochen." },
        { "installer.protection_installed", "Schutz-Modul installiert" },
        { "installer.default_config_created", "Standard-Einstellungen erstellt" },
        { "installer.existing_config_kept", "Bestehende Einstellungen beibehalten" },
        { "installer.shell_config_updated", "Shell-Konfiguration aktualisiert" },
        { "installer.bash_env_correct", "BASH_ENV ist bereits korrekt gesetzt" },
        { "installer.bash_env_enabled", "BASH_ENV fuer nicht-interaktive Bash-Shells aktiviert" },
        { "installer.bash_env_chained", "BASH_ENV wurde mit bestehendem Loader verkettet" },
        { "installer.shortcut_created", "Startmenue-Verknuepfung erstellt (fuer Windows-Benachrichtigungen)" },
        { "installer.shortcut_warning", "Warnung: Startmenue-Verknuepfung konnte nicht erstellt werden ({0})" },
        { "installer.install_done", "\nFertig! Der Schutz ist jetzt aktiv." },
        { "installer.log_backup", "Protokoll gesichert: {0}" },
        { "installer.removed", "Schutz wurde komplett entfernt." },
        { "installer.install_first", "Bitte zuerst installieren." },
        { "installer.updated", "Schutz-Modul wurde aktualisiert." }
    };

    // Returns the localized string for `key`. Falls back to English when
    // the active language has no entry, then to the literal key so that
    // typos surface visibly in the UI rather than being silently empty.
    public static string T(string key)
    {
        string value;
        if (Lang == "de" && De.TryGetValue(key, out value))
            return value;
        if (En.TryGetValue(key, out value))
            return value;
        return key;
    }

    public static string F(string key, params object[] args)
    {
        return string.Format(T(key), args);
    }
}
